### ISSUE TITLE
itunes cant'parse APIC after calling write method with read method's result.

### ISSUE THREAD

**Issue by jin60641** [Zazama/node-id3#105]
itunes can't parse APIC after calling `NodeID3.write` with `nodeID3.read(file, { noRaw: true })`'s result.

**Comment by Zazama** [comment]
I can't reproduce this, it's working both ways for me. Can you provide a specific code snippet that you're using which does not work? 

![grafik](https://user-images.githubusercontent.com/7694808/103439034-b943b080-4c39-11eb-921e-43a317594d07.png)

**Comment by jin60641** [comment]
not write image and trackNumber at the same time. (there's no problem on itunes)
first write image, and next, write TRCK, APIC can't readable.

**Comment by jin60641** [comment]
oh, sorry. not only TRCK, any reaing and writing makes APIC can't parsable.
```ts
const updatedTags = Object.assign(NodeID3.read(filePath, { noRaw: true }), tags);
NodeID3.write(updatedTags, filePath);
```

**Comment by jin60641** [comment]
my NodeID3.read result. I think undefined description are the cause.

```js
{
  title: '20',
  artist: 'eill',
  album: 'SPOTLIGHT',
  genre: 'R&B / Soul',
  year: '20191119',
  performerInfo: 'eill',
  partOfSet: '1/1',
  private: [
    {
      ownerIdentifier: 'CID',
      data: <Buffer 63 69 64 3a 22 68 74 74 70 3a 2f 2f 61 70 70 73 76 72 2e 6d 65 6c 6f 6e 2e 63 6f 6d 2f 67 65 74 64 64 2e 6a 73 70 3f 73 79 6e 63 3d 6d 6d 70 30 31 33 ... 19 more bytes>
    },
    { ownerIdentifier: 'GENRENUM', data: <Buffer 31 34 38> },
    {
      ownerIdentifier: 'MELON_UID',
      data: <Buffer 36 2f 4a 64 33 6e 66 75 4c 78 35 43 64 51 42 6f 44 4e 77 6f 44 51 3d 3d>
    },
    {
      ownerIdentifier: 'MELON_CID',
      data: <Buffer 63 69 64 3d 63 69 64 3a 22 68 74 74 70 3a 2f 2f 61 70 70 73 76 72 2e 6d 65 6c 6f 6e 2e 63 6f 6d 2f 67 65 74 64 64 2e 6a 73 70 3f 73 79 6e 63 3d 6d 6d ... 60 more bytes>
    }
  ],
  image: {
    mime: 'jpeg',
    type: { id: 3, name: 'front cover' },
    description: undefined,
    imageBuffer: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 02 01 01 02 01 01 02 02 02 02 02 02 02 02 03 05 03 03 03 03 03 06 04 04 03 ... 302453 more bytes>
  },
  trackNumber: '4/12',
  comment: { language: 'eng', text: '123123' }
}
```

**Comment by jin60641** [comment]
If I try NodeID3.write with this,
```
 image: {
    mime: 'jpeg',
    type: { id: 3, name: 'front cover' },
    description: 'asdf',
    imageBuffer: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 02 01 01 02 01 01 02 02 02 02 02 02 02 02 03 05 03 03 03 03 03 06 04 04 03 ... 302453 more bytes>
  },
```
iTunes can't parse APIC.

**Comment by jin60641** [comment]
If I remove image's type and mime, it works fine (iTunes can parse APIC).

```ts
NodeID3.read(filePath, { noRaw: true })
if (tags.image?.type) {
    delete updatedTags.image.type;
}
if (tags.image?.mime) {
    delete updatedTags.image.mime;
}
NodeID3.write(tags, filePath)
```

**Comment by Zazama** [comment]
Ah, I see.

This is a really outdated mechanism in node-id3 that I've never changed.
Basically, what's happening, when **reading** a mime type of "image/jpeg", node-id3 returns only "jpeg", but if you **write** only "jpeg" instead of "image/jpeg", iTunes will not recognize it, while most other ID3 viewers will still display the image correctly.

Removing the mime type will make node-id3 check if the image is a jpeg or an png and write "image/jpeg" or "image/png", this check is also kind of wrong.

I think lines 91-95 in ID3Frames.js should be removed because they are simply not correct and 59-63 should handle cases where the image is neither jpeg or png (by not writing any type).

**Comment by jin60641** [comment]
I'll delete image.mime until you update that lines. Thanks :)

**Comment by jin60641** [comment]
Is there any update?
