### ISSUE TITLE
id3v2.4 / UTF-8 Support

### ISSUE THREAD

**Issue by adamhl8** [Zazama/node-id3#107]
Apologies if this is a repeat of #48.

It doesn't seem like id3v2.4 is supported completely yet. I wrote a script to batch process MP3s for my own needs, and I tried processing them saved as id3v2.4 (UTF-8) and node-id3 failed to copy over/corrupted a lot of the album art (I have a backup ofc). Additionally, it also failed to copy over a lot of non-english text. Saving my tags as v2.3 and running it again everything works fine.

**Comment by Zazama** [comment]
Sorry for the trouble, can you provide me some mp3 files which are not read correctly / written corrupted? You can send them to me via email to jan.metzger@gmx.net (as attachment or link)

**Comment by adamhl8** [comment]
I send you a couple mp3s where the album art corrupts. I'm actually having trouble reproducing the corrupted text, but the album art issue is easily reproduceable. If you'd like to replicate what I'm doing, here's my script: https://github.com/adamhl8/format-mp3-artist-tags

I'm not doing anything weird as far as I can tell. It's just `id3.update(tags, file)` where tags is an object with one string.

**Comment by Zazama** [comment]
Hello again!

Would you mind testing if album arts are now copied correctly using the current master index.js (not published on npm)?
Beware that TDRC (Recording time) will still be lost right now.

Unimplemented ID3v2.4.0 text frames

- [ ] TDEN
- [ ] TDOR
- [ ] **TDRC** (data loss in sent files)
- [ ] TDRL
- [ ] TDTG
- [ ] TIME
- [ ] TIPL
- [ ] TMCL
- [ ] TMOO
- [ ] TPRO
- [ ] TSOA
- [ ] TSOP
- [ ] TSOT
- [ ] TSSE
- [ ] TSST

**Comment by adamhl8** [comment]
Yep, that fixed it. Thanks!

**Comment by Zazama** [comment]
Unsynchronisation fix published @ https://github.com/Zazama/node-id3/releases/tag/0.2.3
