### ISSUE TITLE
Implement v2.4 text frames

### ISSUE THREAD

**Issue by Zazama** [Zazama/node-id3#110]
Unimplemented ID3v2.4.0 text frames

- [x] TDEN
- [x] TDOR
- [x] **TDRC** (data loss in sent files)
- [x] TDRL
- [x] TDTG
- [x] TIPL
- [x] TMCL
- [x] TMOO
- [x] TPRO
- [x] TSOA
- [x] TSOP
- [x] TSOT
- [x] TSST

_Originally posted by @Zazama in https://github.com/Zazama/node-id3/issues/107#issuecomment-827140396_

**Comment by chamabreu** [comment]
Hi, is this coming?
I have troubles getting 'year' of my tags. :smile:

**Comment by Zazama** [comment]
This is implemented in commit https://github.com/Zazama/node-id3/commit/53e70cc799dadc4c0443a51170ffe26637bfbaa8 and will soon be published to npm when variable naming changes in this PR are fully sorted out: https://github.com/Zazama/node-id3/pull/126

Sorry for the wait! 🙂
