### ISSUE TITLE
length/TLEN

### ISSUE THREAD

**Issue by ai-compatible** [Zazama/node-id3#114]
The documentation indicates length/TLEN support but I do not see a value coming back for it.

If I ask for all the tags from an mp3 file (no options), I see TALB, TPE1, COMM, TCON, TIT2, TRCK, TYER and APIC... just not TLEN.  I was suspicious of the MP3 file, but MP3TAG and Windows properties tell me the value is present in several files I've tested.

Any ideas of what I might be doing wrong? Thanks in advance.

**Comment by Zazama** [comment]
If someone has the same problem:

> What you can see in MP3Tag and other tools is the length that they read from the MP3 audio data itself. Basically, in every mp3 file, you can prepend an ID3 tag with information about it to the audio data, but both of them are completely seperate things. NodeID3 reads information in the ID3 tag, which most of the time has no length stored in it. Tools like MP3Tag etc. can also read the audio data and calculate the length from that, which is what you see there.
 
> If you need a node library for reading/calculating audio duration, I can recommend you music-metadata (https://github.com/borewit/music-metadata). It can also read ID3 data at the same time if you don't need write support.
