### ISSUE TITLE
Not working with typescript

### ISSUE THREAD

**Issue by Histmy** [Zazama/node-id3#115]
Hello,

I have this typescript code:
```ts
import { update } from "node-id3";

update({ title: "foo" }, "bar.mp3");
```
But when I try to run it, it gives me this error:
```
TypeError: this.read is not a function
    at module.export.update (/home/user/test/node_modules/node-id3/index.js:237:41)
```
I figured out, that it might be because the typescript code was compiled to this:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const node_id3_1 = require("node-id3");
(0, node_id3_1.update)({ title: "foo" }, "bar.mp3");
```
The last line is running the function but value of `this` is set to `global`.
I am not  sure if this is because of my `tsconfig` so I am posting that too:
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "rootDir": "./src",
    "outDir": "./out",
    "moduleResolution": "Node",
    "strict": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "removeComments": true
  },
  "include": [
    "src"
  ]
}
```

**Comment by Zazama** [comment]
I'm not sure if there's a way to import the module like that in its current state, because when you import a single function, it can't access the object (this) which is used in update/read/write/etc.

But you can use

```
import NodeID3 from "node-id3";
NodeID3.update({ title: "foo" }, "bar.mp3");
```

with

```
{
  "compilerOptions": {
    ...
    "esModuleInterop": true,
    ...
  }
}
```

**Comment by Histmy** [comment]
Yeah, you are right. I thought it was possible, because I was "testing" it previously, but after what I have read and tested now, I know it's supposed to behave like this. And thanks for showing me `esModuleInterop` option. It helped me with importing express too.
