### ISSUE TITLE
(Existing) tag for 'year' not returned

### ISSUE THREAD

**Issue by skizzo** [Zazama/node-id3#117]
Hi,

first of all, thanks for this amazing project.

I couldn't help but notice that sometimes the `year` tag is not being returned when reading tags from a MP3 file, even though it's set.

- **left side**: info from [The Tagger app](https://deadbeatsw.com/thetagger/)
- **right side**: Debug View in VSCode after reading tags via `const tags = await NodeID3Promise.read(filePath)`

<img width="684" alt="Screenshot 2022-03-19 at 14 44 01" src="https://user-images.githubusercontent.com/2892572/159123549-8e1e4e65-3115-4e56-ac0f-254b573f1ec8.png">

Does this happen to anybody else? Thanks for some infos.

**Comment by Zazama** [comment]
Hi skizzo,

could you provide me the mp3 file via mail to [jan.metzger@gmx.net](mailto:jan.metzger@gmx.net)?

**Comment by skizzo** [comment]
Hey @Zazama,
thanks for the super quick reply! Please check your inbox, I just sent you the file for which this is happening.

**Comment by Zazama** [comment]
This is related to #110 (TDRC), I'll try to publish a new update this week

**Comment by skizzo** [comment]
Thanks a lot for acting so quickly!

**Comment by Zazama** [comment]
Will be published to npm soon, see https://github.com/Zazama/node-id3/issues/110
