### ISSUE TITLE
ImageBuffer returns undefined after editing other tags

### ISSUE THREAD

**Issue by Sandakan** [Zazama/node-id3#118]
This problem occurs whenever I try to edit tags (primarily the artist) in the song. Usually, before editing the tags, the output from reading the song tags would look like this.

![Screenshot (637)](https://user-images.githubusercontent.com/45460443/178142631-554781b1-4569-43ec-a8aa-667bfb0f5b5a.png)

But after updating the artist tag and reading the tags from the song, I get, 

![Screenshot (639)](https://user-images.githubusercontent.com/45460443/178142671-c47ae38f-d83f-4e62-9fbe-a26613402944.png)

**Comment by Zazama** [comment]
I'm unable to reproduce your issue, can you share some of your code? Seems like you're using it in the browser, what's your setup for that?

This works for me:
```js
const NodeID3 = require('node-id3')

const filepath = './test.mp3'

console.log(NodeID3.read(filepath));

NodeID3.update({
    artist: 'test'
}, filepath);

console.log(NodeID3.read(filepath));
```

If it only happens with some mp3 files, can you send me one that's not working to jan.metzger@gmx.net?

**Comment by Sandakan** [comment]
I don't know how I resolved the problem but now the package seems to work as expected. Maybe I was using a wrong input on the package. Anyway, thanks for reaching out.
