### ISSUE TITLE
Explain in docs that `write` doesn't create new file =)

### ISSUE THREAD

**Issue by godlikeSwan** [Zazama/node-id3#119]
Spent some time to find that
Also #70 helps

**Comment by Zazama** [comment]
Oh yeah, that's an interesting point!
Actually, what is the behaviour you expected? Did you want to write only the tags into a file?

**Comment by godlikeSwan** [comment]
I thought it will write like fs.write

**Comment by Zazama** [comment]
Okay, no I also think it's not explained good enough in the readme, so thanks for creating the issue 🙂 

I've added some explainations, I hope they clarify it better for new users: https://github.com/Zazama/node-id3/commit/3bf7d7299ca9f1ed4127f4825c56642fd7fc650c

**Comment by godlikeSwan** [comment]
much better now! 😄
