### ISSUE TITLE
Duration not supported

### ISSUE THREAD

**Issue by redimongo** [Zazama/node-id3#121]
Not sure if this project is still in development, but we just tried to get the Duration from an mp3 file which according to apple the Duration is recorded in the file.

<img width="272" alt="Screen Shot 2022-09-13 at 8 15 17 pm" src="https://user-images.githubusercontent.com/8399907/189898361-f2d5ea3c-bc1c-42bc-919b-206c9e81b497.png">

However it only returned very basic information

`{"year":"2022.08.17;17.36;A\b","raw":{"TYER":"2022.08.17;17.36;A\b"}}`

the code

```
const tags = NodeID3.read(file.buffer);
    console.log(JSON.stringify(tags));
```

**Comment by Zazama** [comment]
Duration is, most of the time, not stored in the ID3 tags but extracted from the mp3 stream itself.

See here for alternative: https://github.com/Zazama/node-id3/issues/114#issuecomment-985959042
