### ISSUE TITLE
Get the ID3 tags directly

### ISSUE THREAD

**Issue by trustedtomato** [Zazama/node-id3#13]
Is there a way to get & set the ID3 tags directly like TPE1 instead of "artist"?

**Comment by Zazama** [comment]
It's not possible with the given library calls right now, but I'll add the feature.

**Comment by trustedtomato** [comment]
Oh, awesome!

**Comment by Zazama** [comment]
Like in the new README:

```javascript
var read = nodeID3.read("./example/music.mp3", {rawTags: true});
//returns tags
console.log(read.raw["APIC"]); // returns image buffer
console.log(read.raw["TALB"]); // returns album
```

and for the .write function you can just use "TALB" instead of "album".
The .write function doesn't support the raw use of "APIC" and "COMM" right now.

**Comment by Zazama** [comment]
Write APIC/COMM/etc. support added in https://github.com/Zazama/node-id3/commit/a62ec5d396806a0b9395a813769f70c91fcb18d1
