### ISSUE TITLE
Issues with metadata being read by certain players

### ISSUE THREAD

**Issue by phyzical** [Zazama/node-id3#170]
Hey there love the tool,

i help to maintain a spotify -> youtube mp3 scrape, and a feature came up about lyrics.
we were using ffmetadata to write the metadata originally but i couldnt get lyrics to be read by any players so i decided to give this a crack and it worked flawlessly for itunes but i seem to be having some issues with some of the tags being read for other players i.e foobar, it should be noted these now missing tags worked for all players using ffmetadata

The source of my implementation can be found here
https://github.com/SwapnilSoni1999/spotify-dl/pull/193/files#diff-f0493344b07a897ec7a82fcf1440c92651c984eaf617e3c2b8045c4876f6f158

any idea why some tags wouldn't be read/displayed i.e artist
itunes 
![image](https://user-images.githubusercontent.com/5182053/233775930-1b056107-4e88-4cf1-852a-940c46463337.png)

foobar
![image](https://user-images.githubusercontent.com/5182053/233775948-03f7a26c-eb32-45f3-8657-34b60bb40aff.png)

Any help would be appreciated thanks!

**Comment by phyzical** [comment]
hngg sorry turns out it was a cache issue with foobar, manually adjusting the filename after generating the file made it display the latest metadata

**Comment by pbricout** [comment]
Great to know that it works nicely for you.
