### ISSUE TITLE
Basic adding tags not working

### ISSUE THREAD

**Issue by 24jr** [Zazama/node-id3#174]
I'd like to use sveltekit and this library to add an image and some basic tags to an mp3 file. 

I feel like I'm following everything correctly but it's not working. Here is a repo

https://github.com/24jr/audiotagtest

**Comment by pbricout** [comment]
That looks correct, could you please give a bit more details.
What tags are you giving?
What does not work?
What are you observing in logs?
Are you observing any error?
Is the issue with the write or read?
Thanks

**Comment by 24jr** [comment]
I've found success using https://www.npmjs.com/package/browser-id3-writer#browser to write, but that doesn't do read, so I could use both that lib and this lib, but if I get this one working, then I'd only need to use this one. At least I have stuff working either way

**Comment by Zazama** [comment]
`"imageBuffer":{"0":255,"1":216,"2":25...`

It looks to me like the tags are in the wrong format on the server, this should be a buffer, not an object. Maybe that's the problem?

**Comment by 24jr** [comment]
@Zazama oh ok yeah so i think the issue was due to me putting the image arrayBuffer in the JSON on the client which I stringified in the form which apparently screws up the arrayBuffer so now I'm just passing the image as a file separately and getting buffer on server
