### ISSUE TITLE
Possible song corruption when editing metadata while playing the song.

### ISSUE THREAD

**Issue by Sandakan** [Zazama/node-id3#176]
Recently I noticed that songs with metadata modified during the playback have shown corrupted behavior.

If a song has an original duration of 3 minutes, after I modified the lyrics metadata of the song during playback, I noticed that the music gets skipped during half of the duration.

Metadata read from Mp3Tag still shows that the song has 3 minutes, but somewhere in the middle, it gets skipped.

**Comment by Sandakan** [comment]
In my app, these are the files that use `node-id3` to modify song metadata.

- https://github.com/Sandakan/Nora/blob/master/src/main/saveLyricsToSong.ts
- https://github.com/Sandakan/Nora/blob/master/src/main/updateSongId3Tags.ts

**Comment by Zazama** [comment]
Hey,

I guess you are playing with Nora and changing while playing?
Is the file only corrupted while playing, so does it work again after switching songs? Or is the file totally corrupted?

**Comment by Sandakan** [comment]
@Zazama Usually, the song becomes playable after switching to some other song and coming back to the previous song. Still, sometimes part of a song becomes completely unplayable as I mentioned in the issue description.

**Comment by Zazama** [comment]
Sounds to me like the file is not corrupted but the player gets confused by the changed file.

When you change the tags of a file, you offset the rest of the data (e.g. the sound data). If the player does not store all the sound data on first read, it could possibly fail when it reads more data and the offset has changed. This wouldn't be a problem that the ID3 library could solve, but must be solved on the player's side.

**Comment by Zazama** [comment]
I'm gonna close this due to inactivity. If you still think this is a library problem, feel free to re-open it.
