### ISSUE TITLE
How do I use the script?

### ISSUE THREAD

**Issue by GiladFex** [Zazama/node-id3#19]
Hello!

I'm trying to use the code for my website to get audio files name, singer lyrics and album art.

which file do I take into my code? (<script src="**that file**"></script)
and just to be sure -- do I read the raw tags in order to display the information?

Thanks a lot.

**Comment by Zazama** [comment]
Hi,

this library is actually for usage in node.js ("backend javascript") and not for browsers.

**Comment by GiladFex** [comment]
I'm trying to improve scripting so it helped me understand slightly better why it hasn't worked. Thank you!
