### ISSUE TITLE
Add async versions of methods

### ISSUE THREAD

**Issue by miskun** [Zazama/node-id3#20]
Current file operations use synchronous fs api. Would be great to have async api.

**Comment by Zazama** [comment]
Added with https://github.com/Zazama/node-id3/commit/a62ec5d396806a0b9395a813769f70c91fcb18d1 https://github.com/Zazama/node-id3/commit/e3f97558ea6765dd4f5e5e386652832bb74bc4da and https://github.com/Zazama/node-id3/commit/d46c110c23f7d3ea7eb30bf61f9f982eee3d0326

```javascript
NodeID3.create(tags, function(frame) {  })
NodeID3.write(tags, file, function(err) {  })
NodeID3.update(tags, file, function(err) {  })
NodeID3.read(file, function(tags) {  })
NodeID3.removeTags(filepath, function(err) {  })
```
