### ISSUE TITLE
Add update / upsert tags method

### ISSUE THREAD

**Issue by miskun** [Zazama/node-id3#21]
I'm dealing with images and had to write my own wrapper functions to deal with updating single tag in a file. More hassle when I have to deal with images. Would be nice to have update / upsert feature as part of this module.

**Comment by Zazama** [comment]
Added with https://github.com/Zazama/node-id3/commit/f4da14a794479e9a3184305324062595fb187445

Sync/Async usage:

```javascript
//  Update existing ID3-Frame with new/edited tags
let success = NodeID3.update(tags, file) //  Returns true/false
NodeID3.update(tags, file, function(err) {  })
```
