### ISSUE TITLE
How do I use?

### ISSUE THREAD

**Issue by GiladFex** [Zazama/node-id3#22]
Hi there,

How do I use the script? I mean, what do i need to install, etc in order for this to work?
Do I just drag some js file and voila? Do I have to install something (ex. node js) and run a server based on that for it to work?

Thanks a bunch. I'm trying to learn :)

**Comment by Zazama** [comment]
Hi,

node-id3 is for node.js, like you've mentioned, which is basically JavaScript outside of the browser.
This means that you have to install node.js first ( https://nodejs.org/en/ ).

After installing node.js, you need to create a package, which will be your application (you don't have to but I think it's the easiest way and best to learn about the node.js eco-system).

Open the cmd, switch to the desired folder to create your package and enter:
`npm init`
This will ask you some questions, you can just enter the name and skip everything else with the enter key.
After that, you can install node-id3 from the node.js package manager by typing:
`npm install node-id3`

By default, your main file for your package will be called "index.js", which you'll have to create in the same folder as the package.json.
When you've created the "index.js" file, open/edit it and enter:

`var nodeID3 = require('node-id3');`

at the beginning.

Now you can use it like shown in the example of the Readme.

For example, if you want to read the tags of a file, your index.js would look like this:

```javascript
var nodeID3 = require('node-id3');
var read = nodeID3.read("C:/path/to/some/music.mp3");
console.log(read); //to print them
```
to execute your script, write into the cmd:
`npm start`
or
`node index.js`

**Comment by GiladFex** [comment]
Thanks a million times!!!!
Can't express how much this helps.

**Comment by Zazama** [comment]
Sure, if you encounter any problems, feel free to create another issue!

**Comment by G-Buen0** [comment]
Hi,
I am not getting to read the time and the originalFilename fields of the tag... These fields returns undefined. How could I solve that?
Thanks!

**Comment by Zazama** [comment]
@G-Buen0 time and filename will only return a value if they are set in the tag (which is unlikely for most mp3s). If you think they are, I'd suggest you create a new issue and upload the mp3 that has the problem, then I can take a look at it
