### ISSUE TITLE
NodeID3.update will fail with file buffer

### ISSUE THREAD

**Issue by jfdesrochers** [Zazama/node-id3#26]
In the `update` method you accept either a file path or a file buffer as input, however this method call the `write` method for writing the tags which only accepts a file path as input. Calling `update` with a file buffer will fail because `write` will try to pass it to `fs.writeFile`.

**Comment by Zazama** [comment]
That's indeed not supposed to happen, but should be fixed with https://github.com/Zazama/node-id3/commit/edfbcf8e80fd11fc7caed3db9a307b9495e2da2a

**Comment by jfdesrochers** [comment]
It works perfectly, thanks!
