### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by shahankit** [Zazama/node-id3#3]
Can this be used in browser?

**Comment by Zazama** [comment]
Hi,
this can't be used directly in the browser, it's for Node.js.

**Comment by shahankit** [comment]
Any plan on adding browser support or how to edit id3 tags of mp3 blob data in browser?

**Comment by Zazama** [comment]
I think this is what you're searching for:
https://github.com/egoroof/browser-id3-writer

**Comment by shahankit** [comment]
@Zazama thanks a lot. Sorry I'm a bad web searcher.
