### ISSUE TITLE
nodeID3.read() destroys Umlauts by cutting high bit off

### ISSUE THREAD

**Issue by k5e** [Zazama/node-id3#33]
Hi!

nodeID3.read() returns tag values with high bit on, like German umlauts, with high bit off. Thus the tag contents is destroyed. 

```äöüßÄÖÜ``` 
is returned as 
```dv|_DV\\``` 
or in hex: 
```a4 b6 bc 9f 84 96 9c``` 
becomes 
```64 76 7c 5f 44 56 5c 5c```

I'd rather expect that there is no conversion involved.

**Comment by Zazama** [comment]
I'm unable to reproduce your problem, it's returning äÄöÖüÜ just fine for me.
Can you send me your code + the file you're having trouble with?
If you don't won't to post it online, you can find my e-mail in the package.json.

**Comment by k5e** [comment]
Thanks for the reply! I have put a short demo together and I'll send it to the address you mention.

**Comment by Zazama** [comment]
I've looked into it and it should be fixed by https://github.com/Zazama/node-id3/commit/92abfebd6a82d32d0d96d50f6a6b22e44a8c6a86

npm version 0.1.1 contains the fix, so you can just update from npm.

**Comment by k5e** [comment]
Thanks a lot, @zazama, for the fast fix. I'll check it when I'm back at home.

**Comment by k5e** [comment]
I can confirm that this issue is fixed. Thanks again.
