### ISSUE TITLE
Not reading all id3 tags?

### ISSUE THREAD

**Issue by eruby94** [Zazama/node-id3#34]
When I run the script on any of my mp3 files, I only see the tags for raw, encodingTechnology, title and artist.

When I view my files in iTunes, there is info on BPM, a comment, and a genre.

Do you have any idea why these would not all be captured from the script?

**Comment by Zazama** [comment]
Hi, would you be able to send me one of the mp3s you're encountering this issue with by mail? You can find it in the package.json file.
