### ISSUE TITLE
Add more tags

### ISSUE THREAD

**Issue by ExtendLord** [Zazama/node-id3#37]
Can you please add Synced lyrics (SYLT), upc/ean (BARCODE/UPC/EAN) and duration(Maybe there is duration already)?

**Comment by Zazama** [comment]
Hi,

duration is the keyword "length" or "TLEN".

UPC/EAN, are you talking about user defined tags (TXXX)?

**Comment by ExtendLord** [comment]
@Zazama 
![image](https://user-images.githubusercontent.com/26222159/35925528-9e400b42-0c2e-11e8-9cad-07dc9fa64858.png)

IDK, saw the tag name here TXXXXX:BARCODE.

You may use either BARCODE,UPC,EAN for upc/ean.

**Comment by Zazama** [comment]
Alright, I know what you're asking for.
I'll add it propably next week.

**Comment by jonorozcoc** [comment]
> Can you please add Synced lyrics (SYLT), upc/ean (BARCODE/UPC/EAN) and duration(Maybe there is duration already)?

Can you add SYLT? Thanks for all your work!!

**Comment by Zazama** [comment]
I'm gonna close this because it's very unspecific, you can track implementation of missing tags here: https://github.com/Zazama/node-id3/projects/1

If you need a specific one asap, feel free to open another issue
