### ISSUE TITLE
Help, APIC from url

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [Zazama/node-id3#43]
I am using node-ID3 for a yt playlist downloader.
I wan to try to add the thumbnail from the original video to the mp3.
Now I tried reading your code but I was having a hard time as I have never learned anything about how buffers work before.

I need to get the image from a url instead of filepath and I just can't get it working. Your code seems magical, as soon as I touch it everything dies. I tried replacing the fs.readFileSync with a http request with a buffer as response but no luck. For some reason the whole function already finished writing the tags to the file before the request is done, and I can't get it to go synchronous. 

I also tried creating the buffer beforehand and then trying to write it as an image tag because looking at your code I thought that might've worked but I had no luck. 

I am getting desperate and I need some help...

**Comment by Zazama** [comment]
Can you write down the code you've made which doesn't work?

I mean, if you're using `request` for example, this would work:

```javascript
const NodeID3 = require('node-id3')
const request = require('request');

let options = {
    url: 'https://your/link.png',
    encoding: null,
    method: 'GET'
}
 
request(options, (err, res, body) => {
    NodeID3.write({ image: body }, 'yourfile.mp3');
});
```

**Comment by LevitatingBusinessMan** [comment]
I guess I was just tired yesterday lol, thanks for the help I got it working doing about the same as you just did but with axios.

You are awesome, 
thanks!
