### ISSUE TITLE
image.imageBuffer outputs corrupted data

### ISSUE THREAD

**Issue by maxekinge** [Zazama/node-id3#45]
Hey guys im trying to create a webservice w/ nodejs and express. Basically i just want to respond the corresponding albumart for a specific file:
```js
//... (in a express method)
var meta = NodeID3.read(path);
if(meta.image){
  res.set('Content-Type', 'image/' + meta.image.mime);
  res.send(meta.image.imageBuffer);
}
//...
```
I tried it on several mp3 files - all without success. 
Postman shows just this "empty" image
![postman1](https://user-images.githubusercontent.com/11943234/44747562-c2725f00-ab0d-11e8-92d0-a29a714ebcf3.png)
And the corresponding header infos
![postman2](https://user-images.githubusercontent.com/11943234/44747563-c2725f00-ab0d-11e8-9308-dbf6ce3ce43c.png)
I even exported the file onto my local fs with `fs.writeFileSync("test.png", meta.image.imageBuffer, 'binary');`.
This is whats returned:
![test](https://user-images.githubusercontent.com/11943234/44747867-973c3f80-ab0e-11e8-819d-6edc8cfabf38.png)
Before i forget, this album cover should look like this:
![playback](https://user-images.githubusercontent.com/11943234/44748338-da4ae280-ab0f-11e8-89da-8957b8abee5a.png)

**Comment by Zazama** [comment]
Heyo,

using this code, both image files (png/jpg) are valid for me:

```javascript
fs.writeFileSync('test.jpg', nodeID3.read('./knowyoursong.mp3').image.imageBuffer, 'binary');
fs.writeFileSync('test.png', nodeID3.read('./testpng.mp3').image.imageBuffer, 'binary');
```

can you send me a .mp3 you're having trouble with via mail? (jan.metzger@gmx.net)

**Comment by kbuffington** [comment]
I can reproduce this issue. If the file has an id3v2.4 tag, the image buffer is unreadable. Most likely just an encoding issue since node-id3 doesn't support the 2.4 encodings it's defaulting to the wrong one and the output is just garbage.

**Comment by Zazama** [comment]
@kbuffington it was actually a mistake of how APIC description was handled & it was a 2.3 file.
Fixed @ https://github.com/Zazama/node-id3/commit/16b9f8fbd37fc2c6e23d27c50ae6728c4c8a30d7

Maybe one of you can confirm before I publish to npm.

**Comment by kbuffington** [comment]
@Zazama Unfortunately I don't have an mp3 that exercises that code, although what you did _seems_ reasonable. 

The issue I was running into is an ID3v2.4 tag, with both unsynchronisation and dataLengthIndicator flags set. It took about 6 hours today to figure out how to properly read and de-synchronize the APIC frame in that case. Since you don't support 2.4 shouldn't really be an issue.

**Comment by hexrcs** [comment]
Can confirm this issue still exists for ID3 v2.4 tags.

[Example file](https://www.mediafire.com/file/ltacgfx4bu1jm9t/TestingAudio.mp3/file)

**Comment by Zazama** [comment]
@hexrcs v2.4.0 is not well supported in this library, your file's APIC frame is broken here because there are bits set which aren't supported by node-id3. It's a different issue than this one though, so I've opened https://github.com/Zazama/node-id3/issues/48

**Comment by theLMGN** [comment]
I can repro this with ID3 tags generated using [Mutagen](https://mutagen.readthedocs.io/en/latest/user/id3.html)

![image](https://user-images.githubusercontent.com/12257112/63885678-c7901580-c9d0-11e9-9b56-d13ab05d0092.png)

**Comment by theLMGN** [comment]
I'm currently using FFMPEG as a work around 



```js 
function getImage(args) {
    return new Promise(function(a,r) {
        var data 
        var proc = require("child_process").spawn("ffmpeg", ["-i",args,"-y","-strict","-2","-an", "-vcodec", "copy", "-f", "image2", "-"])
        proc.on("exit", function() {a(data)})
        proc.stdout.on("data", function(d) {
            if (!data) {
                data = d
            } else {
                try { data = Buffer.concat([data, d]) } catch(e) {console.error(e)}
            }
        })

    })
}
```
