### ISSUE TITLE
Ability to just build iD3 tags for use in other applications

### ISSUE THREAD

**Issue by cjus** [Zazama/node-id3#5]
I have a need to build iD3 tags but not for file storage.  Rather I need to send the tag data to an encoding service.

I refactored the code a bit to extract the iD3 creation code from the `write` method. I'd like to submit a pull request but wanted to check with you guys first. ;-)

https://github.com/cjus/node-id3/blob/id3-buffer-create/index.js

**Comment by Zazama** [comment]
Hi,

sorry for the late answer.
Your code would be a nice addition to the functionality and also doesn't change the existing calls.

**Comment by Zazama** [comment]
Added in https://github.com/Zazama/node-id3/commit/49f649bed1960ec4ab563b2ab459b9d629bf969b

```javascript
//  Create a ID3-Frame buffer from passed tags
//  Synchronous
let ID3FrameBuffer = NodeID3.create(tags)   //  Returns ID3-Frame buffer
//  Asynchronous
NodeID3.create(tags, function(frame) {  })
```
