### ISSUE TITLE
improving performance of read

### ISSUE THREAD

**Issue by rbenzazon** [Zazama/node-id3#51]
Hi,
I'm wondering if there is a way to improve performance of reading the meta. I don't know if the file is entirely loaded or just the meta portion, I'm passing the path to NodeID3.read(). It seems slow considering the volume I'm reading. Greetings

**Comment by rbenzazon** [comment]
for some context here are the duration in milliseconds for some mp3 that I read sequentially :
170 225 141 109 214 204 259 93 111 208 66 270 194 178 2082 211 238 106 79 108 150 23 181 26 200 177 156 214 176 27 208 34 160 41 97 171 191 208 250 235 262 260 65 236 281 207 251 143 270 294 136
Can I create a shorter Buffer to pass as argument to read() to make it faster? Can I opt out from the image buffer reading?

**Comment by rbenzazon** [comment]
here are the durations for the same files measuring creating the buffer before passing it to read() : 
3 6 4 3 9 5 5 2 3 4 2 6 5 4 55 24 26 13 10 12 17 5 21 5 23 18 31 23 19 4 23 5 16 6 10 18 22 24 28 26 28 26 7 24 22 5 6 3 6 6 3
here are the read() duration using a buffer instead of a path: 
201 278 179 144 285 268 337 120 141 271 90 334 228 225 2522 255 291 139 101 141 188 31 229 35 254 244 192 265 213 32 248 40 186 50 118 203 220 250 305 270 319 303 79 283 335 265 308 168 330 352 168
it seems that giving a buffer instead of a path doesn't improve the performance,

**Comment by Zazama** [comment]
Can you test if this commit helps? https://github.com/Zazama/node-id3/commit/aab08dd6811585b5c8e61c7dea789deb5eeb1b42 (not published on npm, though)

I was able to bring down the time needed for a 10mb file with 10 tags from 300ms to 25ms

**Comment by rbenzazon** [comment]
thanks for the effort, I'll test and keep you informed
