### ISSUE TITLE
Updating a tag removes existing album art

### ISSUE THREAD

**Issue by amirhoseinsalimi** [Zazama/node-id3#55]
Hello,

Figured out any attempt to update a tag, deletes the album art (the picture of the file)

What is the solution?

**Comment by amirhoseinsalimi** [comment]
Solution:

- Read tags. Extract the album art and save it into a file
- Update MP3 tags (title, artist, etc.)
- Write the extracted album art back into the MP3

**Comment by Zazama** [comment]
Hi,

I'm unable to reproduce this bug.
Can you show me your used code and if only happening to specific files, can you send one of them to me?

![grafik](https://user-images.githubusercontent.com/7694808/68158799-aa3b7280-ff50-11e9-8a06-b7715284ac47.png)
