### ISSUE TITLE
Japanese characters

### ISSUE THREAD

**Issue by Pitu** [Zazama/node-id3#6]
When trying to save the following names on the `Artist` tag of a file, broken characters appear.
Strings I'm trying to save:
```
分島花音
ナノ
```

Both get converted to, respectively:
```
ö±ó
ÊÎ
```

When trying to save the following string to the `Title` tag, same thing happens:
```
Dark Night Rhapsody～明けない夜の狂詩曲
```
This is being saved as: 
```
Dark Night Rhapsody^QjDnÂiò
```

Any ideas?

**Comment by Zazama** [comment]
I think there's still an issue with writing non-english characters (encoding problem).

I'll investigate and ideally upload a fix for this issue next week.

**Comment by pituseligmann** [comment]
Any updates on this?

**Comment by Zazama** [comment]
Sorry for the wait, I'll try to push a fix before the end of the year.

**Comment by alesandar** [comment]
There's still an issue with cyrillic characters.
