### ISSUE TITLE
Add support for mp3 chapters

### ISSUE THREAD

**Issue by Connum** [Zazama/node-id3#60]
Could you please add support for mp3 chapters? The specs are here: http://id3.org/id3v2-chapters-1.0
The spec is 15 years old, and yet there's no js/node lib out there that can handle them, so yours would be the first. :)

**Comment by Zazama** [comment]
Chapter (CHAP) support in https://github.com/Zazama/node-id3/commit/6f11909c50c9138ec2ce9e59d46e1c606da45592

It's gonna be in the next release soon, you can test/use it with the master index.js, I've tested it with eyeD3 implementation and everything seems to work fine

**Comment by shealan** [comment]
This is very exciting. Is it possible to embed urls and images into the chapter marks?

There's a mac application that can do this https://overcast.fm/forecast so I am assuming the spec allows for it?

**Comment by Zazama** [comment]
You can basically embed everything you want.

```
chapter: [{
  elementID: "Follow-up: TSMC 10nm",
  startTimeMs: 54700,
  endTimeMs: 88300,
  tags: {                // OPTIONAL
    image: "/path/to/image",
    userDefinedText: [{
      description: "URL",
      value: "url..."
    }]
  }
}]
```

I don't know which kind of frame Forecast uses to embed the URL, though.

**Comment by shealan** [comment]
@Zazama that's fantastic, thank you! Any idea how long until this will be merged into the main branch?

**Comment by Zazama** [comment]
I wanted to rewrite some stuff before publishing because the implementation is a bit messy, but it's taking a bit longer, so I've published it as 0.1.15 for now.

**Comment by FelicitusNeko** [comment]
As a note, it looks like URLs are kept under WXXX, which, according to your roadmap, isn't supported yet. Here's a screenshot of an example, as seen in a hex editor, if this helps any.

![image](https://user-images.githubusercontent.com/50271878/83339482-aa141300-a2a4-11ea-89cc-74f0598436b1.png)

**Comment by shealan** [comment]
Coming back to this after a hiatus working on the project that required it. Are chapter urls still unsupported? I've looked far and wide for a solution that supports writing the full chapter spec, with titles, urls and images. This lib is the closest I can find :)

**Comment by Zazama** [comment]
Hey @shealan

urls are supported since 0.1.17, you can see their usage at the bottom of the tags list in the readme file. If you face any problems, feel free to open a new issue.

**Comment by shealan** [comment]
@Zazama I have done some experimentation with chapters support. Results are encouraging but one last hurdle...

Although I can add chapter marks successfully they are not properly displayed by podcast players.

This clip is an example of a podcast with chapters. https://auphonic.com/media/blog/auphonic_chapters_demo.mp3 I erased all the ID3 tags and attempted to add some back in using node-id3.

When I run my file in Overcast (iOS podcast app) although I do see the chapter names display as they are played, I do not see the interactive chapter tool.

As a reference this is what I see with the example file mentioned above:

<img src="https://user-images.githubusercontent.com/74932/96804603-3513c680-145b-11eb-80fe-a2bedf2f0f38.jpeg" width="600px"/>

I have put up a demo podcast here: https://podlaunch.com/test/podcast.xml

Episode 1: Chapters Example (created with node-id3) - https://podlaunch.com/test/test.mp3
Episode 2: That example file mentioned above - https://podlaunch.com/test/original.mp3

Could it be something to do with table of contents? CTOC?

**Comment by Zazama** [comment]
@shealan Right, CTOC seems to be the problem here, I've created #87
