### ISSUE TITLE
The Genre field returns (13) and I am not getting to get the time field

### ISSUE THREAD

**Issue by G-Buen0** [Zazama/node-id3#61]
Hello, @Zazama. 
So, I want to get the genre field of the ID3 tag. When I set this field as a Pop genre, it returns (13).
Is it correct? How can I solve that?

I have another question... How can I get the time field of the tag? because I am trying to get it but it returns undefined and I am certain that this field is set.
Thanks.

![image](https://user-images.githubusercontent.com/55264187/76535718-1297e480-645a-11ea-82f6-5dd2b18a128d.png)

**Comment by Zazama** [comment]
Hey,

13 is correct and means Pop, you can find the list here: http://webcache.googleusercontent.com/search?q=cache:i7uSuXJiAkAJ:id3.org/id3v2.3.0+#Appendix_A_-_Genre_List_from_ID3v1

The time you see is the mp3 duration, not the ID3 length field. They are two different things. You can't extract the audio length with an ID3 library, 

If you need ID3 tags and duration information, I suggest using https://www.npmjs.com/package/music-metadata instead, it might suite your needs more.

**Comment by G-Buen0** [comment]
Okay. 
Thank you for your support !!
