### ISSUE TITLE
It is possible to set CTOC FRAME

### ISSUE THREAD

**Issue by brainrepo** [Zazama/node-id3#63]
It is possible to set a flag in the chapter to add the current chap to the CTOC? There is a simple way to add a ctoc?

**Comment by Zazama** [comment]
Implemented by https://github.com/Zazama/node-id3/commit/c7b491b49a8a743b89718f6d1607a585e091fb91 and published as 0.1.20

**Comment by brainrepo** [comment]
Thanks for the feature 👍
