### ISSUE TITLE
Support WAV format

### ISSUE THREAD

**Issue by lyswhut** [Zazama/node-id3#67]
WAV RIFF audio also uses ID3v2 comment specification,
Can you support the reading and writing of metadata in this audio format?
Thank you!

**Comment by Zazama** [comment]
I mean, if there's an ID3v2 tag found at the start of the file, node-id3 is gonna read it and also write no matter the file format.
Do you have a specific issue with it?

**Comment by lyswhut** [comment]
WAV files seem to only support comments in ID3 format:
https://en.wikipedia.org/wiki/WAV#Metadata

But the player seems to mainly read the ID3 format:
https://wiki.audacityteam.org/wiki/WAV#Metadata

When writing WAV metadata, `Mp3Tag` and` foobar2000` will be written into `RIFF / LIST-INFO` and` RIFF / ID3v2` at the same time:
https://github.com/Borewit/music-metadata/wiki/RIFF-WAVE

I use `Mp3Tag` to clean up the screenshots of all tags:
![1](https://user-images.githubusercontent.com/20365169/83344582-56083d80-a33b-11ea-8828-9d8ac9bffb0e.png)

Screenshot after writing title and artist using `Mp3Tag`:
![2](https://user-images.githubusercontent.com/20365169/83344584-59032e00-a33b-11ea-938a-bf272abd4da8.png)

It can be seen from the figure that when all the tags are cleaned, the DI3 tag page will be cleared, and only the `RIFF / LIST-INFO` tag is retained, so it is not enough to detect the ID3v2 tag, which needs to be done separately for the WAV format Some additional processing.

The above are the problems you might encounter when supporting the WAV format. Are you interested in supporting it?

**Comment by Zazama** [comment]
Implementing RIFF format seems unsuited for an ID3 project but even as a "special functionality" it doesn't look trivial, so right now, I'm not going to implement it myself, although I wouldn't reject a pull request if it's not integrated too deep into the core library (e.g. passing an option or similar that would enable wrapping the ID3 frame into RIFF before returning instead of auto-detecting the file format etc.).

**Comment by lyswhut** [comment]
Indeed, RIFF is not a pure ID3 project, it should be regarded as another independent project, thank you for your answer, I will now close this issue.
