### ISSUE TITLE
Write removes Artwork

### ISSUE THREAD

**Issue by kh75park** [Zazama/node-id3#69]
I do a simple read, make some updates to title, album, then write back to MP3 file.
But once I write, the artwork is gone.
Even when I do a read then write exact content that I read, the art work is gone after the write.
Something like below makes the artwork disappear or unusable.

```
const tags: any = await nodeID3.read(fullPathNew);
await nodeID3.write(tags, fullPathNew);
```
I use WinAmp to check the tag contents including the artwork.
Before I run above code, the artwork shows, but after running above code, the artwork does not show.  Please fix this problem or share how I can preserve the artwork.  Other than this issue, this is a great module!

**Comment by IvanMMM** [comment]
Did you tried `update` instead of `write` method?

**Comment by Zazama** [comment]
If you don't provide a
```
image/APIC: path/buffer
```
in your tags object, the image is "lost", because write deletes all non-existing tags in the passed Object, you can use update instead or modify the tags Object before writing it again.

**Comment by kh75park** [comment]
I haven't had chance to mess with this till now, but looks like I may have been using older version which had the issue I was seeing and I see there's 0.2.x version and that seems to work fine.  Thanks.
