### ISSUE TITLE
read only selective tags?

### ISSUE THREAD

**Issue by Hammad1029** [Zazama/node-id3#76]
I have around 8GB worth of files so reading all the tags including the image buffer and lyrics is pretty memory and cpu intensive which is why it'd be better if i could just read the artist and title of each of the songs but if a particular song is selected then read its other tags as well. thanks

**Comment by Zazama** [comment]
Implemented in 0.2.0 by https://github.com/Zazama/node-id3/commit/aa46353174d759d85f298e4be971ed5192399d0a

Usage:
```javascript
// Possible options
const options = {
    include: ['TALB', 'TIT2'],    // only read the specified tags (default: all)
    exclude: ['APIC'],            // don't read the specified tags (default: [])
    onlyRaw: false,               // only return raw object (default: false)
    noRaw: false                  // don't generate raw object (default: false)
}
const tags = NodeID3.read(file, options)
```
