### ISSUE TITLE
Multiple Artists

### ISSUE THREAD

**Issue by Debdut** [Zazama/node-id3#77]
Hi,

It isn't clear from the docs on how to handle multiple artists. Can you elaborate?

**Comment by Zazama** [comment]
Hey,

there's only one artist frame allowed per tag by specification, which means you can't pass an array but have to fit them into one string, e.g. comma separated

**Comment by Debdut** [comment]
Thanks for replying so quick, by the way I was seeing / as the separator in ID3, so what should I use `/` or `,` or `;` ?

**Comment by Zazama** [comment]
Yes, using / would be the correct separator by spec

**Comment by Debdut** [comment]
Thanks, I am closing the issue.

**Comment by Debdut** [comment]
Should send a PR on either of the following ?

1. Update Docs on Multiple Artists
2. Update the implementation so that artist accepts string or arrays

**Comment by Zazama** [comment]
I think updating the docs would be the best way, passing an array normally means multiple frames are created.
