### ISSUE TITLE
Updating Tags updates audio format codec and container in Metadata

### ISSUE THREAD

**Issue by Debdut** [Zazama/node-id3#78]
Hi,

I found that updating Tags updates audio format codec and container, which shouldn't be the case.

```js
format: {
    lossless: false,
    container: 'webm',
    codec: 'OPUS',
  }
```
to 

```js
format: {
    lossless: false,
    container: 'MPEG',
    codec: 'MPEG 2.5 Layer 3',
  }
```

using [music-metadata](https://github.com/Borewit/music-metadata) for reading metadata.

**Comment by Zazama** [comment]
Hello Debdut,

node-id3 doesn't have the capabilities to change the audio codec or container. The only thing it does is add the ID3 tag to the beginning of the file. This might be a detection issue with music-metadata
