### ISSUE TITLE
Feature request: 'comment' tag

### ISSUE THREAD

**Issue by garciadelcastillo** [Zazama/node-id3#8]
It would be fantastic to be able to write on the 'comment' tag ;)

Thanks!

**Comment by Zazama** [comment]
Feature added in: https://github.com/Zazama/node-id3/commit/b02ebd3bf98a542064831492b6b77db72848a51a & version 0.0.8

For usage see updated README.md

**Comment by DanielRuf** [comment]
It does not seem to work on Windows 10. At least I do not see it in the Windows explorer.

**Comment by DanielRuf** [comment]
Also `shortText` is not mentioned in the docs. https://github.com/Zazama/node-id3/blob/master/index.js#L646

**Comment by pollax** [comment]
@DanielRuf 
> It does not seem to work on Windows 10. At least I do not see it in the Windows explorer.

I successfully wrote the Comment tag on Windows 10. However, the Comment does not appear from `file properties > details`
If I open the files in a ID3 tag editor such as https://www.mp3tag.de/en/ then it works.

**Comment by DanielRuf** [comment]
> I successfully wrote the Comment tag on Windows 10. However, the Comment does not appear from file properties > details
> If I open the files in a ID3 tag editor such as https://www.mp3tag.de/en/ then it shows.

This is exactly what I mean. Windows 10 does not show them. Does their ID3 tag differ from the standard one?

**Comment by pollax** [comment]
I don't know if/how it differs, but it seems to be a Windows issue. I can find several unanswered posts about this issue in their forums (https://answers.microsoft.com/en-us/windows/forum/windows_10-files/mp3-tag-comment-doesnt-show-in-file-explorer/281af5e0-582a-4f82-aee7-6de3d03186a7 and https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/mp3-tag-comment-doesnt-show-in-file-explorer/01a9c4f7-8d9e-40d3-8e4c-d63944d64b2b)

**Comment by DanielRuf** [comment]
So not many reports and almost no information from Microsoft so far and no bugfix. But thanks for the links so I know that it is a Windows 10 bug and I can probably reenable my code.

Anyway, any idea what the undocumented `shortText` is for?

**Comment by pollax** [comment]
No, I haven't dug into the details of that, sorry.

**Comment by DanielRuf** [comment]
No problem. Thanks for the help so far.

Have a great day!

**Comment by DanielRuf** [comment]
> shortText is for "Short content description", so basically a short description of the comment's content, but because it'd often cause problems and it's not much used, I've removed it from the docs.

Ah ok, thanks for the explanation.
