### ISSUE TITLE
Tags.bpm can be a string but is typed as a number

### ISSUE THREAD

**Issue by waffln** [Zazama/node-id3#80]
I'm not sure if it's always a string, but it can be, like "128.00" in one case i had.
This can make code crash when calling .toFixed() for example, even though TypeScript on strict doesn't report any issues.

From the index.d.ts: https://github.com/Zazama/node-id3/blob/1a9fa45b82e065fb734760c21c4d9e51569bd06b/index.d.ts#L9

I didn't dig into the code but if it's actually always a string, please type it as such and not as a number. Alternatively, make sure it is always a number (parseInt / parseFloat).

**Comment by Zazama** [comment]
Hey, thanks for the notice, this is fixed by https://github.com/Zazama/node-id3/commit/8e36281ccc9bf8e04ed0825d7aef4b34ef27b5e3 and version 0.1.19
