### ISSUE TITLE
Corrupted images in the version 0.1.20

### ISSUE THREAD

**Issue by ortexx** [Zazama/node-id3#89]
Hey! I get my tests failed after your last update. 
The issue is when you call .update() and pass the image (buffer ot path), it's saving currupted. 
If you try to get it after the saving, you will get the incorrect image.
I tried with a couple different files. The result is the same.

**Comment by Zazama** [comment]
I think this is a reading issue, not a saving one. I'll push a fix today.

**Comment by ortexx** [comment]
You know it better, of couse. But looking at my tests it seems like a saving issue, because i can get correct images from my old saved files.

**Comment by Zazama** [comment]
Files were written without the description field before the last release, I think it wasn't an issue because nobody encountered it.
Would you mind trying the current master index.js and tell me if it fixes your problems?

https://raw.githubusercontent.com/Zazama/node-id3/master/index.js

**Comment by ortexx** [comment]
Yes! It seems to work.

**Comment by Zazama** [comment]
Thanks, published as 0.1.21
