### ISSUE TITLE
APIC/image ID Not Setting in Electron

### ISSUE THREAD

**Issue by coffeepostal** [Zazama/node-id3#94]
I'm having an odd issue in an ElectronJS app where it's setting title, artist, album, genre, and track just fine, but for some reason it's not working with APIC/image (I've tried with both, to see if that was the issue). I tried the plugin in a normal Node app, and there was no issues setting the image ID, so I'm guessing it's an interaction with Electron. Any and all suggestions would be appreciated!

For reference, here is my code:

```
let mp3File = `${savePath}/${filename}.mp3`
let tags = {
  title: story.title,
  artist: story.author,
  album: story.album,
  genre: story.genre,
  APIC: "./images/albumArt-default-light.jpg",
  TRCK: story.track
}

let success = NodeID3.write(tags, mp3File)

NodeID3.write(tags, mp3File, function(err) {
  if (err) reject(console.error(err))
  if (success) {
    resolve(console.log(`MP3 metadata added.`))
  }
})
```

**Comment by Zazama** [comment]
This might just be a problem with the path, I'd advice to try the following code, which should throw an exception if the path is wrong:

```
const fs = require('fs')
let mp3File = `${savePath}/${filename}.mp3`
let tags = {
  title: story.title,
  artist: story.author,
  album: story.album,
  genre: story.genre,
  APIC: fs.readFileSync("./images/albumArt-default-light.jpg"),
  TRCK: story.track
}

let success = NodeID3.write(tags, mp3File)
```

**Comment by coffeepostal** [comment]
@Zazama thank you for responding so quickly! I made the change, and it did throw a `no such file` error (I needed to add the `src` folder), but once I fixed that, it still isn't adding the image to the meta data.

Like I said, it works correctly in simple Node projects, so I'm thinking it's a interaction with Electron, any other ideas to try?

**Comment by Zazama** [comment]
Could you console.log the output of `fs.readFileSync("./src/images/albumArt-default-light.jpg")` (or what your correct path is)? It should be a buffer printed with hexadecimal values (0x 00 FF FE ...). And maybe send it to me with the code phrase that you're using.

**Comment by coffeepostal** [comment]
@Zazama OK, so here's a new wrinkle. I'd been opening the MP3 files in iTunes and Mac OS Finder, and not seeing album art. I opened it in a meta data editor, Yate, and it's showing correctly in there. So it looks like it's getting written, but not completely. I tried it removing the `fs.readFileSync`, and again, it doesn't work in iTunes/Finder, but in Yate the art shows up.

I did the console.log of `console.log(fs.readFileSync("./src/images/albumArt-default-light.jpg"))`, but the result isn't in HEX it's a buffer stream and there doesn't seem to be a way to copy it out of the Electron console so here's a screenshot while I keep poking at it to get an actual data dump:

![Screen Shot 2020-11-09 at 6 58 19 PM](https://user-images.githubusercontent.com/24851/98622129-a3f77900-22bd-11eb-9c44-ef906afa6965.png)

**Comment by Zazama** [comment]
Okay, that's interesting. First of all, the screenshot looks like a valid jpeg file, so it shouldn't be a problem with reading the file.
It's possible that the mp3 file has an ID3v1 Tag already set and iTunes, for whatever reason, shows that instead of the newer version ID3v2 (which node-id3 writes). That wouldn't make sense, though, because the node.js version seems to work.

Can you send me all three mp3 files (the electron version, the node.js version and the plain one, without any changes, if you still have it) and the final code snippet you've used to jan.metzger@gmx.net?

**Comment by coffeepostal** [comment]
@Zazama thank you! I'm behind the ball on for-pay project, and I'm using `node-id3` for a personal project. It might be a couple of days, but I'll get it to you ASAP.

For a little backstory, the Electron app is a website scrapper that takes the content of a website, converts it to audio via `Say.js` into a `wav` file. It then converts that `wav` into an `mp3`, at which point, it uses `node-id3` to add the website's meta data (eg: author, title, etc) to the MP3's metadata. I don't think it'll matter too much, but I thought context might help. You'd also mentioned that it might be a conflict with pre-existing ID3v1 tags, which I don't think would exist since the files are being generated, though maybe they have default values that I don't know about.

Thanks again!

**Comment by jin60641** [comment]
@coffeepostal 
<img width="791" alt="스크린샷 2020-12-30 오전 5 21 42" src="https://user-images.githubusercontent.com/9072743/103311921-e9832780-4a5e-11eb-9294-f5a5c652ef9d.png">

I'm using this code on electron, and I hope this is helpful for you.

**Comment by Zazama** [comment]
Feel free to reopen if you still have issues

**Comment by coffeepostal** [comment]
I'm sorry it's been so long, but I finally picked the project back up, the error was mine. I was trying to use relative file paths for the image, I switched to path to make the file path absolute, and it worked just fine. So sorry for the run around and the lack of updates!
