### ISSUE TITLE
Album Cover Not Showing Up In Third Party Apps

### ISSUE THREAD

**Issue by ethans333** [Zazama/node-id3#96]
When I write my tags to an mp3 file everything seems to work fine, the info all gets put in normally and the album cover shows up in my file explorer. But when I open the song in the Local files section of Spotify or Itunes the album cover is never displayed and what's weird is I can add album artwork to the file in iTunes, so I think it might be a file permission problem. Is there anyway to fix this?

```javascript
const tagSong = async (info) => {
    const file = `../Saved Songs/${info.title}.mp3`;
      
    const tags = {
      title: info.title,
      artist: info.artist,
      album: info.title,
      image: {
        mime: "jpeg",
        type: {
          id: 3,
          name: "Album Cover"
        },
        imageBuffer: (await got(info.albumCover, { responseType: 'buffer' })).body
      },
    };
  
    NodeID3.create(tags);
    NodeID3.write(tags, file);
};
``` 
Screenshots:
https://imgur.com/a/bSlpCKb

**Comment by ethans333** [comment]
Sorry man, nevermind I fixed it. It had nothing to do with your module. Please delete this discussion from your issues.

**Comment by baldwin-design-co** [comment]
what did you end up doing to solve this

**Comment by jin60641** [comment]
> what did you end up doing to solve this

https://github.com/Zazama/node-id3/issues/105
check here.
