### ISSUE TITLE
Comment Language

### ISSUE THREAD

**Issue by anasqadrei** [Zazama/node-id3#97]
Setting comments has a weird behaviour. How does language work?

``` javascript
// works
comment: {
  language: "eng",
  text: "mycomment"
}

// works
comment: {
  language: "eng",
  text: "عربي"
}

// doesn't work
comment: {
  language: "ara",  // ISO Arabic. https://id3.org/ISO%20639-2
  text: "عربي"
}
```

**Comment by Zazama** [comment]
What do you mean by weird behaviour? Everything seems to work as expected for me, tested with internal read and MP3Tag

![grafik](https://user-images.githubusercontent.com/7694808/102690522-459baf80-4206-11eb-82f3-15524ca84e42.png)

**Comment by anasqadrei** [comment]
It's empty for me when I open in in iTunes (v12.8.2.3) -> song info.

**Comment by Zazama** [comment]
This is because iTunes seems to discards comments of other languages than "eng"

- https://community.mp3tag.de/t/x-itunes-doesnt-read-comment-tag-when-mp3tag-language-is-spanish/16007/2
- https://discussions.apple.com/thread/1825326?answerId=8833755022#8833755022
