### ISSUE TITLE
Can't remove tag with update method

### ISSUE THREAD

**Issue by jin60641** [Zazama/node-id3#98]
I Can't clear existing COMM field (maybe USLT too) by update method with empty string.

```javascript
const tags = {
  comment: {
    language: "eng",
    text: "",
  }
};

NodeID3.update(tags, filePath, () => { ~~~ })
```

https://github.com/Zazama/node-id3/blob/dc684978f43fc8355c238f194249153c3ea0fea1/src/ID3Frames.js#L110-L112

Should I call `removeTags` and re-write all tags?
how about support
1. auto removeTags if value is empty on `update` method?
2. support options to select specific tags on `removeTags` method.
3. or remove referrenced line(create empty COMM or USLT field when update). (easist way, but inefficient)

**Comment by Zazama** [comment]
I see the problem, I think (1) would break some implementations, also it kinda breaks the purpose of update. Supporting (2) and maybe adding an option to the .update function where you can exclude specific tags might be good.

As a workaround you can call

```javascript
let tags = NodeID3.read(file).raw
if (tags.COMM) {
    delete tags.COMM
}
NodeID3.write(tags, file)
```
which is basically the same as calling update when only deleting the COMM frame.

**Comment by Zazama** [comment]
Note to self: COMM can have empty text

> This frame is indended for any kind of full text information that does not fit in any other frame. It consists of a frame header followed by encoding, language and content descriptors and is ended with the actual comment as a text string. Newline characters are allowed in the comment text string. There may be more than one comment frame in each tag, but only one with the same language and content descriptor.

**Comment by Zazama** [comment]
When 0.2.2 is published later today, you can pass read options

```javascript
// Doesn't read comment from file
NodeID3.update(tags, filePath, { exclude: ['COMM'] })
```

or if you only want specific tags

```javascript
// Only reads title and image from file
NodeID3.update(tags, filePath, { include: ['TIT2', 'APIC'] })
```

Values that are in `tags` are still written like before, options passed or not.
